version: "3.9"

services:
    db-mysql:
      image: mysql:8.0.30
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=1234
#        - MYSQL_DATABASE=testdb
#        - MYSQL_USER=admin
#        - MYSQL_PASSWORD=root
      ports:
        - "3306:3306"
      volumes:
        - db-data:/var/lib/mysql
volumes:
  db-data: