spring:
  datasource:
    url: "jdbc:mysql://${DB_HOST}/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  logging:
    loggly:
      token: ${CUSTOMER_TOKEN_LOGGLY}
      apptag: algafood-api

  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: ${SMTP_EMAIL_USUARIO}
    password: ${SMTP_EMAIL_SENHA}

algafood:
  email:
    impl: smtp
    remetente: AlgaFood <marcosf_alves@outlook.com>

  storage:
    tipo: s3
    s3:
      id-chave-acesso: ${ID_CHAVE_ACESSO}
      chave-acesso-secreta: ${CHAVE_ACESSO_SECRETA}
      bucket: mfa-algafood-api
      regiao: us-east-1
      diretorio-fotos: product-photos

  jwt:
    keystore:
      jks-location: ${JKS_BASE64}
      password: ${KEYSTORE_PASSWORD}
      keypair-alias: ${KEYSTORE_ALIAS}

logging:
  level:
    org:
      hibernate: error
      springframework:
        web: debug
        servlet:
          view:
            freemarker: warn
