server:
  port: 8081

spring:
  profiles:
    active: development

  web:
    resources:
      add-mappings: false

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    hikari:
      max-lifetime: 900000

  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      repositories:
        enabled: false

  session:
    store-type: redis

  freemarker:
    template-loader-path: classpath:templates/emails/
    content-type: text/html
    charset: UTF-8
    settings:
      locale: pt_BR

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json