server:
  port: ${SERVER_PORT:8081}
  forward-headers-strategy: framework

spring:
  profiles:
    active: development

  web:
    resources:
      add-mappings: false

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    hikari:
      max-lifetime: 900000

  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      repositories:
        enabled: false

  session:
    store-type: redis

  freemarker:
    template-loader-path: classpath:templates/emails/
    content-type: text/html
    charset: UTF-8
    settings:
      locale: pt_BR

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:${SERVER_PORT:8081}/.well-known/jwks.json"

springdoc:
  packages-to-scan: com.algaworks.algafood.api
  paths-to-match: /v1/**
  swagger-ui:
    oauth:
      client-id: algafood-web
      client-secret: web123
      use-pkce-with-authorization-code-grant: true
  algafood:
    oauth-flow:
      authorization-url: "http://localhost:${SERVER_PORT:8081}/oauth/authorize"
      token-url: "http://localhost:${SERVER_PORT:8081}/oauth/token"
