spring:
  datasource:
    url: "jdbc:mysql://${DB_HOST}/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  mail:
    host: ${SMTP_EMAIL_HOST}
    port: ${SMTP_EMAIL_PORT}
    username: ${SMTP_EMAIL_USER}
    password: ${SMTP_EMAIL_PASSWORD}

  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: "https://algafood-api.malves.dev.br/oauth2/introspect"
          client-id: algafood-backend
          client-secret: backend123

algafood:
  logging:
    loggly:
      token: ${CUSTOMER_TOKEN_LOGGLY}
      apptag: algafood-api

  email:
    impl: smtp
    remetente: AlgaFood <marquinhofalves@gmail.com>

  storage:
    tipo: s3
    s3:
      id-chave-acesso: ${AWS_S3_ACCESS_KEY}
      chave-acesso-secreta: ${AWS_S3_SECRET_KEY}
      bucket: ${AWS_S3_BUCKET_NAME}
      regiao: ${AWS_S3_REGION}
      diretorio-fotos: product-photos

  auth:
    provider-url: "https://algafood-api.malves.dev.br"

  jwt:
    keystore:
      jks-location: ${JKS_BASE64}
      password: ${KEYSTORE_PASSWORD}
      keypair-alias: ${KEYSTORE_ALIAS}

logging:
  level:
    org:
      hibernate: error
      springframework:
        web: debug
        servlet:
          view:
            freemarker: warn
