version: "3.9"

networks:
  algafood-network:
    driver: bridge

volumes:
  db-data:

services:
  algafood-mysql:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    #        - MYSQL_DATABASE=testdb
    #        - MYSQL_USER=admin
    #        - MYSQL_PASSWORD=root
    ports:
      - "13306:3306"
    networks:
      - algafood-network
    volumes:
      - db-data:/var/lib/mysql

  algafood-redis:
    image: redis:6.2.11-alpine
    restart: always
    networks:
      - algafood-network

  algafood-api:
    build: ../
    image: algafood-api
    command: ["/wait-for-it.sh", "algafood-mysql:3306", "-t", "30", "--", "java", "-Xms896m", "-Xmx1024m", "-jar", "algafood-api.jar"]
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - DB_HOST=algafood-mysql
      - AUTH_SERVER_HOST=http://127.0.0.1
      - SPRING_DATA_REDIS_HOST=algafood-redis
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql

  algafood-proxy:
    build: ../nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api